"""initial schema

Revision ID: d6a38cf740c4
Revises: 
Create Date: 2026-09-14 15:04:09.726626
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd6a38cf740c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('api_key_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idem_expires', 'idempotency_records', ['expires_at'], unique=False)
    op.create_index('uq_idem_key', 'idempotency_records', ['api_key_id', 'key'], unique=True)
    op.create_table('inbound_events',
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_inbound_type_created', 'inbound_events', ['event_type', 'created_at'], unique=False)
    op.create_table('invoice_sequences',
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('fy', 'kind')
    )
    op.create_table('products',
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('webhook_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('ip_allowlist', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('api_keys',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('key_id', sa.String(length=80), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_hint', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_index('ix_apikey_lookup', 'api_keys', ['key_id', 'is_active'], unique=False)
    op.create_table('costs',
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('incurred_on', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('recurring_monthly', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_product_date', 'costs', ['product_id', 'incurred_on'], unique=False)
    op.create_table('customers',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_email', 'customers', ['email'], unique=False)
    op.create_index('uq_customer_external', 'customers', ['product_id', 'external_id'], unique=True)
    op.create_table('outbound_deliveries',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('event_id', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_outbound_due', 'outbound_deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_outbound_product', 'outbound_deliveries', ['product_id', 'created_at'], unique=False)
    op.create_table('plans',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('sac', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_plan_code', 'plans', ['product_id', 'code'], unique=True)
    op.create_table('ledger_entries',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_kind', 'ledger_entries', ['kind', 'entry_date'], unique=False)
    op.create_index('ix_ledger_product_date', 'ledger_entries', ['product_id', 'entry_date'], unique=False)
    op.create_table('orders',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=60), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_order_product_created', 'orders', ['product_id', 'created_at'], unique=False)
    op.create_table('wallets',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_paise >= 0', name='ck_wallet_non_negative'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id')
    )
    op.create_table('checkout_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('success_url', sa.Text(), nullable=True),
    sa.Column('cancel_url', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_checkout_status', 'checkout_sessions', ['status', 'expires_at'], unique=False)
    op.create_table('payments',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('fee_tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('refunded_paise', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=20), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_payment_captured', 'payments', ['captured_at'], unique=False)
    op.create_index('ix_payment_product_status', 'payments', ['product_id', 'status'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paise > 0', name='ck_wallet_txn_positive'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_txn_wallet', 'wallet_transactions', ['wallet_id', 'created_at'], unique=False)
    op.create_index('uq_wallet_txn_idem', 'wallet_transactions', ['wallet_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('invoices',
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('fy', sa.String(length=7), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('reverses_invoice_id', sa.UUID(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=False),
    sa.Column('seller_address', sa.Text(), nullable=False),
    sa.Column('seller_gstin', sa.String(length=15), nullable=True),
    sa.Column('seller_state_code', sa.String(length=2), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_address', sa.Text(), nullable=False),
    sa.Column('buyer_gstin', sa.String(length=15), nullable=True),
    sa.Column('buyer_state_code', sa.String(length=2), nullable=True),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.Column('tax_treatment', sa.String(length=20), nullable=False),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('cgst_paise', sa.BigInteger(), nullable=False),
    sa.Column('sgst_paise', sa.BigInteger(), nullable=False),
    sa.Column('igst_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reverses_invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_invoice_customer', 'invoices', ['customer_id', 'issue_date'], unique=False)
    op.create_index('ix_invoice_product', 'invoices', ['product_id', 'issue_date'], unique=False)
    op.create_table('refunds',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_refund_id', sa.String(length=60), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_refund_id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('subscriptions',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('grace_days', sa.Integer(), nullable=False),
    sa.Column('last_payment_id', sa.UUID(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_on', sa.Date(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_sub_customer', 'subscriptions', ['customer_id'], unique=False)
    op.create_index('ix_sub_status_end', 'subscriptions', ['status', 'current_period_end'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sac', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('taxable_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_rate', sa.Integer(), nullable=False),
    sa.Column('cgst_paise', sa.BigInteger(), nullable=False),
    sa.Column('sgst_paise', sa.BigInteger(), nullable=False),
    sa.Column('igst_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_lines')
    op.drop_index('ix_sub_status_end', table_name='subscriptions')
    op.drop_index('ix_sub_customer', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('refunds')
    op.drop_index('ix_invoice_product', table_name='invoices')
    op.drop_index('ix_invoice_customer', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('uq_wallet_txn_idem', table_name='wallet_transactions', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_wallet_txn_wallet', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('ix_payment_product_status', table_name='payments')
    op.drop_index('ix_payment_captured', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_checkout_status', table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    op.drop_table('wallets')
    op.drop_index('ix_order_product_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_ledger_product_date', table_name='ledger_entries')
    op.drop_index('ix_ledger_kind', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('uq_plan_code', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_outbound_product', table_name='outbound_deliveries')
    op.drop_index('ix_outbound_due', table_name='outbound_deliveries')
    op.drop_table('outbound_deliveries')
    op.drop_index('uq_customer_external', table_name='customers')
    op.drop_index('ix_customer_email', table_name='customers')
    op.drop_table('customers')
    op.drop_index('ix_cost_product_date', table_name='costs')
    op.drop_table('costs')
    op.drop_index('ix_apikey_lookup', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('products')
    op.drop_table('invoice_sequences')
    op.drop_index('ix_inbound_type_created', table_name='inbound_events')
    op.drop_table('inbound_events')
    op.drop_index('uq_idem_key', table_name='idempotency_records')
    op.drop_index('ix_idem_expires', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
